"""empty message

Revision ID: 9c5f88703a1f
Revises: c3b36beebc74
Create Date: 2023-04-03 12:36:20.905150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5f88703a1f'
down_revision = 'c3b36beebc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password_hach')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hach', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
